# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MafengwoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=140)),
                ('image_src', models.URLField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
