# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20160330_0935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MafengwoModel',
            new_name='Calendar',
        ),
    ]
