# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_auto_20160330_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='picture',
            new_name='img_src',
        ),
    ]
