# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_auto_20160330_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['-created_at']},
        ),
    ]
