# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_auto_20160330_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='ding_num',
            field=models.IntegerField(default=0),
        ),
    ]
