# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_calendar_ding_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='destitation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
