# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationship', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='by',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='situation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
