# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0005_auto_20160314_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='star',
            name='created_at',
        ),
    ]
