# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160315_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='followers_num',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='follows',
            new_name='follows_num',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posts_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
