# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20160321_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='to',
        ),
        migrations.AddField(
            model_name='post',
            name='commented_by',
            field=models.ManyToManyField(related_name='post_commented_by', through='blog.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='post_liked_by', through='blog.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
