# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160321_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
    ]
