# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:55
from __future__ import unicode_literals

import apps.blog.models.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160401_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes_hum',
            new_name='likes_num',
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default/default_portrait.jpg', upload_to=apps.blog.models.upload_path.user_directory_path),
        ),
    ]
