# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160401_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follows_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='posts_num',
            field=models.IntegerField(default=0),
        ),
    ]
