# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 04:34
from __future__ import unicode_literals

import apps.blog.models.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20160404_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.upload_path.user_directory_path),
        ),
    ]
