# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160407_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 6, 38, 18, 570123, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
